# Generated by Django 4.1.4 on 2023-02-19 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="tax",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="port",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quotation.country",
            ),
        ),
    ]
