# Generated by Django 4.1.4 on 2023-02-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0002_quotation_tax_alter_country_code_alter_port_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="port",
            name="country_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
