# Generated by Django 4.1.4 on 2023-02-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0003_port_country_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="port",
            name="code",
            field=models.CharField(max_length=100),
        ),
    ]
