# Generated by Django 4.1.4 on 2023-02-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0004_alter_port_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="port",
            name="telephone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
