# Generated by Django 4.1.4 on 2023-02-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0007_alter_animal_options_alter_catchtype_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="container_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="shipped_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipped_from",
                to="quotation.country",
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="origin",
                to="quotation.country",
            ),
        ),
    ]
