# Generated by Django 4.1.4 on 2023-02-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "quotation",
            "0008_quotation_container_quantity_quotation_shipped_from_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotation",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="price_unit",
        ),
        migrations.AddField(
            model_name="quotation",
            name="note",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sizeprice",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quotation.currency",
            ),
        ),
        migrations.AddField(
            model_name="sizeprice",
            name="price_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quotation.priceunit",
            ),
        ),
    ]
