# Generated by Django 4.1.4 on 2023-02-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0009_remove_quotation_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingmethod",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
