# Generated by Django 4.1.4 on 2023-02-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0011_quotation_recieved_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sizeprice",
            name="size",
            field=models.CharField(max_length=20),
        ),
    ]
