# Generated by Django 4.1.4 on 2023-02-19 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quotation", "0012_alter_quotation_note_alter_sizeprice_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"], "verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="currency",
            options={"ordering": ["name"], "verbose_name_plural": "Currencies"},
        ),
        migrations.AlterModelOptions(
            name="specie",
            options={"ordering": ["name"], "verbose_name_plural": "Species"},
        ),
        migrations.AlterField(
            model_name="animal",
            name="create_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
