# Generated by Django 4.1.4 on 2023-02-20 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quotation", "0015_alter_sizeprice_create_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="product_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="quotations/products"
            ),
        ),
        migrations.AlterField(
            model_name="specie",
            name="create_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="create_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
