# Generated by Django 4.1.4 on 2023-03-04 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0016_quotation_product_image_alter_specie_create_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SizePriceBoxNetWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("net_weight", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "sizeprice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quotation.quotation",
                    ),
                ),
            ],
        ),
    ]
