# Generated by Django 4.1.4 on 2023-03-04 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0017_sizepriceboxnetweight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sizepriceboxnetweight",
            name="sizeprice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quotation.sizeprice"
            ),
        ),
    ]
