# Generated by Django 4.1.4 on 2023-03-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0018_alter_sizepriceboxnetweight_sizeprice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sizepriceboxnetweight",
            options={"ordering": ["sizeprice"]},
        ),
        migrations.AddField(
            model_name="sizeprice",
            name="price_in_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sizeprice",
            name="quotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizeprices",
                to="quotation.quotation",
            ),
        ),
        migrations.AlterField(
            model_name="sizepriceboxnetweight",
            name="sizeprice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="netweight",
                to="quotation.sizeprice",
            ),
        ),
    ]
