# Generated by Django 4.1.4 on 2023-03-23 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("quotation", "0019_alter_sizepriceboxnetweight_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Import",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity_code", models.CharField(max_length=13)),
                ("month", models.DateField(blank=True, null=True)),
                ("production_description", models.CharField(max_length=250)),
                ("country_name", models.CharField(max_length=50)),
                ("total_price", models.IntegerField()),
                (
                    "total_weight_tons",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "total_weight_kg",
                    models.DecimalField(decimal_places=2, max_digits=9),
                ),
                ("price_per_kg", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quotation.country",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("commodity_code", "month", "country", "production_description")
                },
            },
        ),
    ]
