# Generated by Django 4.1.4 on 2023-03-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importcharts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="import",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
