# Generated by Django 4.1.4 on 2023-03-23 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0019_alter_sizepriceboxnetweight_options_and_more"),
        ("importcharts", "0002_alter_import_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="import",
            name="animal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quotation.animal",
            ),
        ),
    ]
