# Generated by Django 4.1.4 on 2023-03-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importcharts", "0003_import_animal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="import",
            name="price_per_kg",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
