"""
Django settings for danaproject project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import environ
from pathlib import Path
from django.core.management.utils import get_random_secret_key
from dotenv import load_dotenv

load_dotenv()

env = environ.Env(
    DEBUG = (bool, False)
)

environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!


CSRF_TRUSTED_ORIGINS =[]
CSRF_TRUSTED_ORIGINS.extend(
    filter(
    None,
    os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(',')
		)
)
ALLOWED_HOSTS =[]
ALLOWED_HOSTS.extend(
    filter(
    None,
    os.environ.get("ALLOWED_HOSTS", "").split(',')
		)
)




# Application definition

INSTALLED_APPS = [
		'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'corsheaders',
		'django_htmx',
		'storages',
		'rest_framework',
		'rest_framework.authtoken',
		'user',
		'quotation',
    'active_link',
		'crispy_forms',
		'crispy_bootstrap5',
    'widget_tweaks',
    'importcharts',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
		'django_htmx.middleware.HtmxMiddleware',
  	'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = "danaproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ['templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "danaproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
				'ENGINE': 'django.db.backends.postgresql',
				'HOST': os.environ.get("POSTGRES_HOST"),
				'NAME': os.environ.get("POSTGRES_DB"),
				'USER': os.environ.get("POSTGRES_USERNAME"),
				'PASSWORD': os.environ.get("POSTGRES_PASSWORD"),
				'PORT':int(os.environ.get("POSTGRES_PORT"),)
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"

#STATIC_ROOT = BASE_DIR / 'static'
STATIC_ROOT = '/vol/web/static'
STATICFILES_DIRS = [
	'danaproject/static'
]

MEDIA_URL = '/media/'
MEDIA_ROOT = '/vol/web/media'
#MEDIA_ROOT = BASE_DIR /'media'
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'user.User'

# REST_FRAMEWORK = {
# 	"DEFAULT_SCHEMA_CLASS":"drf_spectacular.openapi.AutoSchema"
# }

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.ERROR: 'danger',
    messages.WARNING: 'warning'
}


#Email Configuration
EMAIL_HOST=os.environ.get("EMAIL_HOST")
EMAIL_PORT=587
EMAIL_HOST_USER=os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD=os.environ.get("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL= 'Dana Project <quotations.danaproject@gmail.com>'