# Generated by Django 4.1.4 on 2023-04-05 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_superadmin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Admin"),
                    (2, "Shrimp"),
                    (3, "Salmon"),
                    (4, "Scallop"),
                    (5, "Halibut"),
                    (6, "Guest"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
